USE [NPSTDB]
GO


DROP TABLE [dbo].[DatoPaaske]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DatoPaaske](
	[DatoPaaskeId] [int] IDENTITY(1,1) NOT NULL,
	[PaaskeAften] [date] NULL,
	[PaaskeFerieUke] [tinyint] NULL,
	[Aar] [smallint] NULL,
	[MaalTall] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[DatoPaaskeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


